### ISSUE TITLE
Refine post_processing.py for cc to speech text and test

### ISSUE THREAD

**Issue by dviator** [maevyn11/WeSaidSheSaid#1]
The "ironclad" portion of the post_processing script needs to be implemented. 

Then the script needs to be tested against more material.

**Comment by maevyn11** [comment]
import operator
				for i in matchIndex:
					postMatchSegment = searchSegment[i:]
					for j, token in enumerate(searchSegment[i:]):
						if token == newPhrase[j]:
							IndexMatchCounter[i] += 1				
				print IndexMatchCounter
				trueIndex = max(IndexMatchCounter.iteritems(), key=operator.itemgetter(1))[0]
				print trueIndex
				composite_phrase = oldPhrase[0:-len(newPhrase)] + searchSegment[0:trueIndex] + newPhrase

**Comment by dviator** [comment]
https://gist.github.com/50bb5c5348d72cf99a9e.git

**Comment by maevyn11** [comment]
<script src="https://gist.github.com/maevyn11/50bb5c5348d72cf99a9e.js"></script>

**Comment by dviator** [comment]
"https://gist.github.com/maevyn11/50bb5c5348d72cf99a9e.js"

**Comment by dviator** [comment]
https://gist.github.com/maevyn11/50bb5c5348d72cf99a9e
